### ISSUE TITLE
cannot install wgrib2 (does not exist)

### ISSUE THREAD

**Issue by raybellwaves** [conda-forge/wgrib2-feedstock#34] opened 2023-08-19 03:11 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

❯ mamba install wgrib2

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['wgrib2']

conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.9.*

Could not solve for environment specs
The following package could not be installed
└─ wgrib2   does not exist (perhaps a typo or a missing channel).

### Installed packages

```shell
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2023.7.22            h8857fd0_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libsqlite                 3.42.0               h58db7d2_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
ncurses                   6.4                  hf0c8a7f_0    conda-forge
openssl                   3.1.2                h8a1eda9_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
python                    3.9.17          h07e1443_0_cpython    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
```

### Environment info

```shell
active environment : test_env
    active env location : /Users/ray/miniforge3/envs/test_env
            shell level : 2
       user config file : /Users/ray/.condarc
 populated config files : /Users/ray/miniforge3/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=12.5.1=0
                          __unix=0=0
       base environment : /Users/ray/miniforge3  (writable)
      conda av data dir : /Users/ray/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/ray/miniforge3/pkgs
                          /Users/ray/.conda/pkgs
       envs directories : /Users/ray/miniforge3/envs
                          /Users/ray/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.10.10 Darwin/21.6.0 OSX/12.5.1
                UID:GID : 502:20
             netrc file : /Users/ray/.netrc
           offline mode : False
```

**Comment by raybellwaves** [comment] 2023-08-19 03:36
I think IIRC wgrib2 is only installable on linux and i'm using a mac

**Comment by akrherz** [comment] 2024-01-01 22:50
duplicate of #36

**Closed by akrherz** 2024-01-01 22:50 UTC
Labels: bug
